# Generated by Django 5.0.1 on 2024-11-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('BUYER', 'buyer'), ('SELLER', 'seller'), ('RIDER', 'rider'), ('VALIDATOR', 'validator')], max_length=10, verbose_name='Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
            ],
        ),
    ]
